### ISSUE TITLE
7zip support

### ISSUE THREAD

**Issue by ghost** [optyfr/Jtrrntzip#1]
Hi

Maybe 7zip support can be added by using https://7-zip.org/sdk.html ?

**Comment by optyfr** [comment]
This project is about torrentzip (tzip)... torrent7zip (t7z) is a totally different format which I don't intend to do because it has many many drawbacks (need to uncompress the overall archive to extract only one file which make it very unusable for lot of projects including mame) at a point that the game is not worth the effort. 

Furthermore there is no full java implementation available (the one in the sdk is obsolete since at least 2008), the best up to date java solution relies on native libraries (sevenzipjbinding) which is complex, a bit buggy, not well maintained, and cause problems for portability on various platforms/processors (arm for example)

**Comment by girlblender** [comment]
FUCK YOU PIECE OF SHIT
